
nightly:
    workspace  : /tmp/TEMP
    htmloutput : ${SCRIPTROOT}/public_html
    simulators : [mips]
 
archc:
    #systemc   : https://github.com/archc/systemc.git
    systemc   : /home/max/ArchC/tools/systemc/2.3.1/
    binutils  : 
    gdb       : 
    #link/path : https://github.com/archc/archc.git
    link/path : /home/max/ArchC/archc/github/src/


simulators:
    mips:
        #modules   : [acsim, powersc, hltrace]
        modules   : [acsim]
        inputfile : mips.ac
        link/path : https://github.com/archc/mips.git
        #link/path : /home/max/ArchC/processors/github/mips
        #cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/mips/archc_mips_toolchain_20141215_64bit.tar.bz2
        cross     : /home/max/x-tools/mips-newlib-elf
        benchmarks: [mibench]
    arm:
        modules   : [acsim, powersc, hltrace] 
        inputfile : arm.ac
        link/path : https://github.com/archc/arm.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/arm/archc_arm_toolchain_20150102_64bit.tar.bz2
        #cross     : /home/max/x-tools/arm-newlib-eabi
        benchmarks: [mibench]
    powerpc:
        modules   : [acsim, powersc, hltrace] 
        inputfile : powerpc.ac
        link/path : https://github.com/archc/powerpc.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/powerpc/archc_powerpc_toolchain_20141215_64bit.tar.bz2
        #cross     : /home/max/x-tools/powerpc-newlib-elf
        benchmarks: [mibench]
    sparc:
        modules   : [acsim, powersc, hltrace] 
        inputfile : sparc.ac
        link/path : https://github.com/archc/sparc.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/sparc/archc_sparc_toolchain_20141215_64bit.tar.bz2
        #cross     : /home/max/x-tools/sparc-newlib-elf
        benchmarks: [mibench]

modules: 
    acsim: 
        generator: acsim
        options: -abi -nw
        desc:
    powersc:
        generator: acsim
        options: -abi -nw -pw
        desc:
    hltrace: 
        generator: acsim
        options: -abi -nw -hlt
        desc:
   
benchmarks:
    mibench:
        automotive/basicmath : [small,large]
        automotive/bitcount  : [small,large]
        automotive/qsort     : [small,large]
        automotive/susan     : [small,large]
        telecomm/adpcm       : [small,large]
        telecomm/CRC32       : [small,large]
        telecomm/FFT         : [small,large] 
        telecomm/gsm         : [small,large]
        network/dijkstra     : [small,large]
        network/patricia     : [small,large] 
        security/rijndael    : [small,large]
        security/sha         : [small,large]
        consumer/jpeg        : [small,large]
        consumer/lame        : [small,large]
    spec2006:
        gcc        : [test]
        bzip_2     : [test]
        gcc        : [test]
        mcf        : [test] 
        gobmk      : [test]
        hmmer      : [test]
        sjeng      : [test]
        libquantum : [test]
        h264       : [test] 

        # apps with problems
        #omnetpp    = [test] 
        #astar      = [test]


