
nightly:
    workspace  : /tmp/TEMP
    htmloutput : ${SCRIPTROOT}/public_html
    simulators : [mips]
 
archc:
    #systemc   : https://github.com/archc/systemc.git
    systemc   : /home/max/ArchC/tools/systemc/2.3.1/
    binutils  : 
    gdb       : 
    #link/path : https://github.com/archc/archc.git
    link/path : /home/max/ArchC/archc/github/src/


simulators:
    mips:
        #modules   : [acsim, powersc, hltrace]
        modules   : [acsim]
        inputfile : mips.ac
        run       : mips.x --load=
        link/path : https://github.com/archc/mips.git
        #link/path : /home/max/ArchC/processors/github/mips
        #cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/mips/archc_mips_toolchain_20141215_64bit.tar.bz2
        cross     : /home/max/x-tools/mips-newlib-elf
        benchmarks: [mibench, spec2006]
    arm:
        modules   : [acsim, powersc, hltrace] 
        inputfile : arm.ac
        run       : arm.x --load=
        link/path : https://github.com/archc/arm.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/arm/archc_arm_toolchain_20150102_64bit.tar.bz2
        #cross     : /home/max/x-tools/arm-newlib-eabi
        benchmarks: [mibench]
    powerpc:
        modules   : [acsim, powersc, hltrace] 
        inputfile : powerpc.ac
        run       : powerpc.x --load=
        link/path : https://github.com/archc/powerpc.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/powerpc/archc_powerpc_toolchain_20141215_64bit.tar.bz2
        #cross     : /home/max/x-tools/powerpc-newlib-elf
        benchmarks: [mibench]
    sparc:
        modules   : [acsim, powersc, hltrace] 
        inputfile : sparc.ac
        run       : sparc.x --load=
        link/path : https://github.com/archc/sparc.git
        cross     : http://archc.lsc.ic.unicamp.br/downloads/Tools/sparc/archc_sparc_toolchain_20141215_64bit.tar.bz2
        #cross     : /home/max/x-tools/sparc-newlib-elf
        benchmarks: [mibench]

modules: 
    acsim: 
        generator: acsim
        options: -abi -nw
        desc:
    powersc:
        generator: acsim
        options: -abi -nw -pw
        desc:
    hltrace: 
        generator: acsim
        options: -abi -nw -hlt
        desc:
   
benchmarks:
    mibench:
        #automotive/basicmath : [small]
        #automotive/bitcount  : [small]
        #automotive/qsort     : [small]
        #automotive/susan     : [small]
        #telecomm/adpcm       : [small]
        #telecomm/CRC32       : [small]
        #telecomm/FFT         : [small] 
        #telecomm/gsm         : [small]
        #network/dijkstra     : [small]
        #network/patricia     : [small] 
        #security/rijndael    : [small]
        security/sha         : [small]
        #consumer/jpeg        : [small]
        #consumer/lame        : [small]
    spec2006:
        #401.bzip2      : [test]
        #403.gcc        : [test]
        #429.mcf        : [test] 
        445.gobmk      : [test]
        #456.hmmer      : [test]
        #458.sjeng      : [test]
        #462.libquantum : [test]
        #464.h264ref    : [test] 

        # apps with problems
        #omnetpp    = [test] 
        #astar      = [test]


